const PROJECTS = [{tTitle:"", tDescription:""}];

const FAQ = [{question:"",answer:""}];

const SAMPLES = [{tTitle:"", relatedLesson:"", tDescription:""}];

const LESSONS = [{tTitle:"Level 1", objective:"Foundations of HTML and JavaScript", tDescription:"Level 1 is all about getting your sea legs.  This level will teach you how to set up a basic template for your page.  You'll learn the difference between HTML and JavaScript and how to make them communicate with one another.<br /><br /><a href = 'Level 1/index.html'>Proceed to Level 1</a>",steps:[]}, 
{tTitle:"Level 2", objective:"Dressing Up Your Pages", tDescription:"Cascading Style Sheets (CSS) is the language that controls the look and feel of your pages.  From fonts to colors, you'll need to master these properties if you want your work to be visually appealing.  Level 2 takes you through some of the most basic CSS.<br /><br /><a href = 'Level 2/index.html'>Proceed to Level 2</a>",steps:[]}, 
{tTitle:"Level 3", objective:"Information Flow", tDescription:"Level 3 introduces you to one of the cornerstones of efficient programming. Information flow is all about how you make and use your variables and functions.  Global? Local?  Do your functions perform one task or multiple tasks?  Through the use of parameters and return values, you can take complete control of the ways in which your page processes information.<br /><br /><a href = 'Level 3/index.html'>Proceed to Level 3</a>",steps:[]}, 
{tTitle:"Level 4", objective:"Strings and Arrays", tDescription:"You've been using strings since the very beginning, but what are they really?  Learn the complexities of strings and how to manipulate them as data.  And what are strings, but arrays of characters?  Level 4 will show you the similarities between the two types of objects and how data structures like arrays can reduce the amount of repeat code on your pages dramatically.<br /><br /><a href = 'Level 4/index.html'>Proceed to Level 4</a>",steps:[]}, 
{tTitle:"Level 5", objective:"Advanced CSS", tDescription:"A web page is designed around something called the Box Model.  Don't know what that is?  That's fine because Level 5 is all about using CSS selectors and designing your page around the Box Model so that it can have its best look.<br /><br /><a href = 'Level 5/index.html'>Proceed to Level 5</a>",steps:[]}, 
{tTitle:"Level 6", objective:"Objects", tDescription:"The Document Object Model (DOM) is the foundation of all programming for the web.  Your browser sees everything on your page as an virtual object, something to be positioned and maniplulated.  Through the use of JavaScipt's built in tools, Level 6 teaches you all about the DOM and how to make and use your own objects.<br /><br /><a href = 'Level 6/index.html'>Proceed to Level 6</a>",steps:[]}, 
{tTitle:"Level 7", objective:"Events", tDescription:"Our software is event driven.  That means that the browser is waiting for something to happen and you program the responses.  Level 7 teaches you how to program events from the most simple mouse and keyboard events to making your own.<br /><br /><a href = 'Level 7/index.html'>Proceed to Level 7</a>",steps:[]}, 
{tTitle:"Level 8", objective:"Server Side Programming with NodeJS", tDescription:"A web page rests on a server.  When a user puts in a request for that page, the request is sent to the server and the page is downloaded to the user's machine.  But sometimes there's programming that allows the page to perform some tasks on the server <i>before</i> being downloaded.  Like checking a login or getting personal informaton.  NodeJS is JavaScript that has been designed to work on a server.<br /><br /><a href = 'Level 8/index.html'>Proceed to Level 8</a>",steps:[]}];